runtime: custom
env: flex
instance_class: F2

entrypoint: gunicorn -b :$PORT app:app

service: smartsave-api

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.65


env_variables:
  USE_GPU: "false"

readiness_check:
  app_start_timeout_sec: 600
